### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by lecano** [lecano/laravel-http-client-application#6]
Add crud unit testing

**Comment by pedroxido** [comment]
I'd like to work on this issue for the hacktoberfest, I'll update with follow up questions

**Comment by Heniisbaba** [comment]
Hi @lecano, I'd like to help here

**Comment by gghughunishvili** [comment]
@lecano I've added basic tests for all the methods that were implemented in this PR: https://github.com/lecano/laravel-http-client-application/pull/19
